---
title: "Plots for the manuscript"
output: html_document
---

#Setup 

```{r setup, include=FALSE}
fig_num<-0
tab_num<-0
fig_name<-TRUE
tab_name<-TRUE
word_width = 6.5
knitr::opts_chunk$set(
	echo = FALSE,
	fig.keep = "all",
	fig.show = "asis",
	fig.width = word_width,
	message = FALSE,
	warning = FALSE,
	dev='png',
	dpi=300
)

knitr::opts_knit$set(root.dir = 'E://GitHub//curtail_sgp') #UPDATE THIS PATH WITH LOCAL REPOSITORY PATH
#Width of the available space in the word document

#Own functions

library(ggplot2)
library(ggthemes)
library(scales)
library(RColorBrewer)
library(ggrepel)
library(cowplot)
library(tidyr)
library(stringr)
#Defines the themes of the plots
theme_milovanoff <- function(base_size=14,legend_position="bottom",...) {
  theme_tmp <- theme_foundation(base_size=base_size)+
    theme(plot.title = element_text(face = "bold",size = rel(1.2), hjust = 0.5),
          text = element_text(),
          panel.background = element_rect(colour = NA),
          plot.background = element_rect(colour = NA),
          panel.border = element_rect(colour = NA),
          axis.title = element_text(face = "bold",size = rel(0.9)),
          axis.title.y = element_text(angle=90,vjust = 0.5),
          axis.title.x = element_text(vjust = 0.5),
          axis.text = element_text(), 
          axis.line = element_line(colour="black"),
          axis.ticks = element_line(),
          panel.grid.major = element_line(colour="#f0f0f0"),
          panel.grid.minor = element_blank(),
          legend.key = element_rect(colour = NA),
          legend.key.height = unit(0.3, "cm"),
          legend.key.width = unit(0.5, "cm"),
          legend.margin = margin(t=0.1,r=0.1,b=0.1,l=0.1, "cm"),
          legend.text = element_text(size = rel(0.8)),
          legend.spacing.x = unit(0.1, "cm"),
          legend.spacing.y = unit(0.1, "cm"),
          plot.margin=unit(c(2,4,2,2),"mm"),
          strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
          strip.text = element_text(face="bold"),
          panel.spacing.x = unit(0.2, "cm"),
          panel.spacing.y =unit(0.2, "cm")
    )
  if (legend_position=="bottom"){
    theme_tmp <- theme_tmp+
      theme(legend.box = "vertical",
            legend.box.just = "top",
            legend.position = "bottom",
            legend.direction = "horizontal",
            legend.title = element_text(face="italic",rel(1.1),hjust=0.5))
  } else if (legend_position=="right"){
    theme_tmp<-theme_tmp+
      theme(legend.box = "vertical",
            legend.box.just = "left",
            legend.position = "right",
            legend.direction = "vertical",
            legend.title = element_text(face="italic",rel(1.1),hjust=0))
  }
  theme_tmp <- theme_tmp + theme(...)
  return(theme_tmp)
}
#See here: https://betterfigures.org/2015/06/23/picking-a-colour-scale-for-scientific-graphics/

get_color_palette <- function(palette_type,number_color){
  if (palette_type=="seq_blue"){
    #colorblind safe. Limit=9
    color_palette <- brewer.pal(number_color,"Blues")
  } else if (palette_type=="seq_green"){
    #colorblind safe. Limit=9
    color_palette <- brewer.pal(number_color,"Greens")
  } else if (palette_type=="seq_red"){
    #colorblind safe. Limit=9
    color_palette <- brewer.pal(number_color,"YlOrRd")
  } else if(palette_type=="div"){
    #colorblind safe. Limit=11
    color_palette <- brewer.pal(number_color,"RdYlBu")
  } else if(palette_type=="cat"){
    #Not colorblind safe. Limit=8. Dark2 or Set1 work
    color_palette <- brewer.pal(number_color,"Dark2")
  } else if(palette_type=="paired"){
    #Not colorblind safe. Limit=12
    color_palette <- brewer.pal(number_color,"Paired")
  }
  return(color_palette)
}

scale_fill_milovanoff <- function(palette_type,number_color,...){
  discrete_scale("fill","milovanoff",manual_pal(values = get_color_palette(palette_type=palette_type,number_color=number_color)), ...)
}

scale_colour_milovanoff <- function(palette_type,number_color,...){
  discrete_scale("colour","milovanoff",manual_pal(values = get_color_palette(palette_type=palette_type,number_color=number_color)), ...)
  
}
```

#Model run
```{r}
source("model_setup.R")
```

#Figure 2

##Figure 2-a
```{r fig2a,fig.height=3,fig.width=3}
res <- do.call(transport_lca_ghg_f,list())
plot_dt <- subset(res[["transport_lca_ghg_mode"]],Year%in%2005:2019)

plot_dt$Mode <- rename_values(plot_dt$Mode,list("Rapid transit"=c("LRT","MRT"),"Bus"=c("Public bus","School bus","Private bus"),"Private car"=c("Private car","Private hire car")))
plot_dt$Mode <- factor(plot_dt$Mode,levels=c("Rapid transit","Bus","Taxi","Motorcycle","Private car"))
plot_dt <- aggregate(formula = Value~Year+Mode,data = plot_dt,FUN=sum)
ggplot()+
  geom_col(data=plot_dt,
           aes(x=Year,y=Value/10^9,fill=Mode))+
  scale_fill_milovanoff(palette_type="cat",
                        number_color=length(unique(plot_dt$Mode)),
                        guide=guide_legend(title="Mode",nrow=3))+
  scale_y_continuous(expand = c(0.01,0))+
  scale_x_continuous(expand = c(0.01,0),breaks = c(2005,2010,2015,2019))+
  labs(x=NULL,y=expression("Annual emissions (Mt CO"[2]*" eq.)"))+
  theme_milovanoff(axis.title.y = element_text(angle=90,hjust = 1,vjust=1,face="bold"),
                   legend_position = "bottom",
                   legend.key.height = unit(0.4, "cm"),
                   legend.key.width = unit(0.4, "cm"),
                   legend.margin = margin(t=-0.2,r=0.5,b=0.1,l=0.5, "cm"))

ggsave("outputs/plots/paper/fig2a.png",width=3,height=3,units=c("in"),dpi=600)
#Save
plot_dt$Value <- formatC(plot_dt$Value/10^9, format = "e", digits = 2)
plot_dt$Unit <- "Mt CO2 eq."
write.csv(plot_dt,"outputs/raw_data/man_fig2a.csv",row.names = FALSE)
```

##Figure 2-b
```{r fig2b,fig.height=2.8,fig.width=3}
res <- do.call(transport_lca_ghg_f,list())
dt <- subset(res[["transport_lca_ghg_process"]],Year%in%c(2005:2019) & Value!=0 & Process!="CNG") #REMOVE CNG 
#Format
dt$Mode <- rename_values(dt$Mode,list("Rapid transit"=c("LRT","MRT"),"Bus"=c("Public bus","School bus","Private bus"),"Private car"=c("Private car","Private hire car")))
dt$Process[dt$Process%in%c("Vehicle production, without battery","Battery production","Bus production, without battery","Motorcycle production, without battery")] <- ""
dt$Phase <- rename_values(dt$Phase,list(" prod."=c("Fuel Production")," use"=c("Fuel Use"),"Vehicle prod."=c("Vehicle production")))
dt$Category <- sapply(1:nrow(dt),function(x)paste0(dt$Process[x],dt$Phase[x]))
#Discard non-relevant columns
dt <- aggregate(formula = Value~Mode+Category,data = subset(dt,select=c(Year,Category,Value,Mode)),FUN=sum)

#Total
plot_tot <- aggregate(formula = Value~Category,data = dt,FUN=sum)
#
dt$Value <- sapply(1:nrow(dt),function(x)dt$Value[x]/sum(subset(dt,Mode==dt$Mode[x])$Value))
plot_tot$Value <- sapply(1:nrow(plot_tot),function(x)plot_tot$Value[x]/sum(subset(plot_tot)$Value))
plot_tot$Mode <- "TOTAL"

#Combine
plot_col <- rbind(dt,plot_tot)
plot_col$Mode <- factor(plot_col$Mode,levels=rev(c("Rapid transit","Bus","Taxi","Motorcycle","Private car","TOTAL")))
plot_col$Category <- factor(plot_col$Category,levels=c("Diesel prod.","Diesel use","Gasoline prod.","Gasoline use","Electricity prod.","Vehicle prod."))

ggplot(data=subset(plot_col))+
  geom_col(aes(x=Mode,y=Value*100,fill=Category))+
  geom_segment(aes(x="TOTAL",xend="TOTAL",yend=100,y=-50),
               position = position_nudge(x = 0.5, y = 0),
               lineend = "square",
               size=1)+
  guides(fill = guide_legend(title=NULL,ncol=2,reverse = TRUE))+
  coord_flip(clip="off",ylim=c(0,100))+
  scale_fill_manual(values=c("#A6CEE3","#1F78B4","#FB9A99","#E31A1C","#d8b365","#bdbdbd","#636363","#000000"))+
  scale_y_continuous(expand = c(0.01,0),labels = paste0(seq(0,100,25),"%"))+
  scale_x_discrete(expand = c(0.01,0))+
  labs(y="Stage contribution analysis",x=NULL)+
  theme_milovanoff(axis.title.x=element_text(hjust=1,face="plain",margin = unit(c(0,0,0,0),"mm")),
                   legend_position = "bottom",
                   legend.key.height = unit(0.4, "cm"),
                   legend.key.width = unit(0.4, "cm"),
                   legend.margin = margin(t=-0.2,r=0.5,b=0.1,l=-0.5, "cm"),
                   plot.margin=unit(c(0,5,0,2),"mm"),
                   strip.text = element_text(face="bold",size=rel(0.8),margin = unit(c(0,0,0,0),"mm")))

ggsave("outputs/plots/paper/fig2b.png",width=3,height=2.8,units=c("in"),dpi=600)
#Save
plot_col$Value <- formatC(plot_col$Value, format = "e", digits = 2)
write.csv(plot_col,"outputs/raw_data/man_fig2b.csv",row.names = FALSE)

#Numerical values
```


#Figure 3
```{r fig3,fig.height=3,fig.width=4}
#GHG emissions
res <- do.call(read_def_outputs_f,list(function_tbc="transport_lca_ghg_f",scen_tbc="scen1"))
plot_dt <- subset(res[["transport_lca_ghg_process"]],Year%in%2018:2050)
plot_dt[plot_dt$Phase=="Fuel Production" & plot_dt$Process=="Electricity","Phase"] <- "Electricity prod."
plot_dt$Phase <- rename_values(plot_dt$Phase,list('Fuel use'="Fuel Use",'Fuel prod.'="Fuel Production",'Vehicle prod.'="Vehicle production"))
plot_dt$Phase <- factor(plot_dt$Phase,levels=rev(c("Fuel use","Fuel prod.","Electricity prod.","Vehicle prod.")))
plot_dt <- aggregate(formula = Value~Year+Phase+Scenario,data = plot_dt,FUN=sum) %>%
  cum_long_dtf_f(.) %>%
  subset(.,Year==2050)
#Format
plot_dt$Shift <- sapply(plot_dt$Scenario,function(x)str_sub(x,0,str_locate_all(x,"_")[[1]][1,"start"]-1),USE.NAMES = FALSE)
plot_dt$Shift <- rename_values(plot_dt$Shift,list('Private car ubiquity (PC)'="PC",'Public transit development (PT)'="PT"))
plot_dt$Shift <- factor(plot_dt$Shift,levels=c('Private car ubiquity (PC)','Public transit development (PT)'))
plot_dt$Improve <- sapply(plot_dt$Scenario,function(x)str_sub(x,str_locate_all(x,"_")[[1]][1,"start"]+1,15),USE.NAMES = FALSE)
plot_dt$Improve <- factor(plot_dt$Improve,levels=c("EV","Constant"))

#Budget
budget_dt <- data.frame()
for (budget_scen in c("2C","1.5C")){
  update_attribute_values(list(carbon_budget_mdl=budget_scen))
  modelframework::load_input_data_f()
  budget_dt[nrow(budget_dt)+1,"Value"] <- do.call(transport_lca_ghg_budget_f,list())
  budget_dt[nrow(budget_dt),c("Mode","Scenario")] <- c("Budget",budget_scen)
}

#Format

ggplot()+
  geom_col(data=plot_dt,
           aes(x=Improve,y=Value/10^9,fill=Phase))+
  geom_hline(data=budget_dt,
               aes(yintercept=Value/10^9,linetype=Scenario),
               size=1.2)+
  facet_wrap(~Shift,ncol=1)+
  coord_flip()+
  scale_y_continuous(expand = c(0.01,0),limits=c(0,200))+
  scale_fill_manual(values=c("#bdbdbd","#1F78B4","#FB9A99","#E31A1C"),guide = guide_legend(title=NULL,ncol=4,order=1,reverse = TRUE))+
  scale_linetype_manual(values=c(1,3),guide=guide_legend(title="Budget",nrow=2,order=2,keywidth=unit(10,"mm") ),labels=c("1.5 °C","2 °C"))+
  labs(x=NULL,y=expression("2018-2050 Cumulative GHG emissions (Mt CO"[2]*" eq.)"))+
  theme_milovanoff(legend_position = "bottom",
                   legend.box.margin = margin(t=-0.3,r=1.7,b=0,l=0, "cm"),
                   axis.title.x = element_text(hjust=0.85),
                   plot.margin=unit(c(1,3,1,1),"mm"),
                   legend.box.just = "top",
                   strip.text = element_text(face="bold",margin = unit(c(1,1,1,1),"mm")),
                   legend.key.width=unit(3,"mm"))

ggsave("outputs/plots/paper/fig3.png",width=4.1,height=3,units=c("in"),dpi=600)

#Save
plot_dt$Scenario <- NULL
plot_dt$Year <- NULL
plot_dt$Value <- formatC(plot_dt$Value/10^9, format = "e", digits = 2)
plot_dt$Unit <- "Mt CO2 eq."
write.csv(plot_dt,"outputs/raw_data/man_fig3.csv",row.names = FALSE)

#Numerical values
plot_dt$Value <- as.numeric(plot_dt$Value)
tot_dt <- aggregate(formula=Value~Shift+Improve,data=plot_dt,FUN=sum)

```

#Figure 4

```{r fig4, fig.height=4, fig.width=4.2}
lca_tot <- do.call(read_simulation_f,list(function_tbc="transport_lca_ghg_f",sub_function_tbc="n",dts_name="transport_lca_ghg_tot",scen_tbc="optimization_electricity_2c",sim_tbc="sim3",sim_type="continuous"))
plot_dt <- aggregate(formula=Value~Scenario+Simulation+electrification_year+ef_elec_variable,data=subset(lca_tot,Year%in%c(2018:2050)),FUN=sum)

plot_dt$Scenario <- rename_values(plot_dt$Scenario,list('Private car ubiquity (PC)'="PC",'Public transit development (PT)'="PT"))
plot_dt$Scenario <- factor(plot_dt$Scenario,levels=c('Private car ubiquity (PC)','Public transit development (PT)'))

plot_dt$electrification_year <- as.numeric(plot_dt$electrification_year)
plot_dt$ef_elec_variable <- as.numeric(plot_dt$ef_elec_variable)
plot_dt$ef_elec_variable <- 0.472*(1-plot_dt$ef_elec_variable)

ggplot()+
  geom_tile(data=plot_dt,
                      aes(x=electrification_year,y=ef_elec_variable, fill = Value/10^9))+
  labs(y=expression(atop("2020-2050 average electricity GHG intensity","(kg CO"[2]*" eq./kWh)")),x="Complete electrification target year")+
  scale_x_continuous(expand=c(0,0))+
  scale_y_continuous(expand=c(0,0))+
  facet_wrap(~Scenario,ncol=1)+
  scale_fill_gradientn(limits = c(50,160),
                       colours = c("#a50026","#ffffbf","#abd9e9","#313695"),
                       values = c(1,0.27,0.18,0),
                       breaks = seq(50,160,10),
                       labels = seq(50,160,10),
                       guide=guide_legend(title=expression(atop("GHG emissions","(Mt CO"[2]*" eq.)")),reverse = TRUE))+
  theme(axis.title = element_text(face = "plain"),
        axis.title.y = element_text(angle=90,margin = unit(c(0,2,0,1),"mm")),
        axis.title.x = element_text(vjust = 0.5,margin = unit(c(2,0,1,0),"mm")),
        axis.text = element_text(size = rel(0.9)),
        axis.ticks = element_line(),
        legend.direction = "vertical",
        legend.text = element_text(size = rel(0.9)),
        legend.title.align = 0,
        legend.title = element_text(hjust=-1),
        legend.justification = "left",
        legend.key.size = unit(0.5,"cm"),
        plot.margin = unit(c(1,0,1,1),"mm"),
        strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
        panel.spacing.x = unit(0.2, "cm"),
        panel.spacing.y =unit(0.2, "cm"),
        strip.text = element_text(face="bold",margin = unit(c(1,1,1,1),"mm")))

ggsave("outputs/plots/paper/fig4.png",width=4.2,height=4,units=c("in"),dpi=600)
#Save
plot_dt$Simulation <- NULL
colnames(plot_dt) <- rename_values(colnames(plot_dt),list(`Electrification target year`="electrification_year",`Electricity GHG intensity`="ef_elec_variable"))
plot_dt$Value <- formatC(plot_dt$Value/10^9, format = "e", digits = 2)
plot_dt$Unit <- "Mt CO2 eq."
write.csv(plot_dt,"outputs/raw_data/man_fig4.csv",row.names = FALSE)
```

#Figure 5

```{r fig5,fig.height=3.6,fig.width=6}
dt <- do.call(read_simulation_f,list(function_tbc="transport_lca_ghg_f",sub_function_tbc="n",dts_name="transport_lca_ghg_tot",scen_tbc="electricity",sim_tbc="sim2",sim_type="continuous"))
plot_dt <- aggregate(formula=Value~Scenario+Simulation+electrification_year+modal_share_variable+pkt_tot_variable,data=subset(dt,Year%in%c(2018:2050)),FUN=sum)
dt_col <- c("electrification_year","modal_share_variable","pkt_tot_variable")
plot_dt[,dt_col] <- sapply(dt_col,function(x) as.numeric(plot_dt[,x]))

plot_dt <- subset(plot_dt, modal_share_variable%in%c(0.000,0.005,0.010,0.015,0.020) & pkt_tot_variable%in%c(0.000,0.01,0.02))
plot_dt$pkt_tot_variable <- factor(paste0(-plot_dt$pkt_tot_variable*100,"%"),levels = c("-2%","-1%","0%"))
plot_dt$Scenario <- factor(plot_dt$Scenario,levels = c("Constant","Transition to renewable"))

plot <- ggplot()+
  geom_tile(data=plot_dt,
            aes(x=electrification_year,y=modal_share_variable*100, fill = Value/10^9))+
  labs(y=NULL,x=NULL)+
  scale_x_continuous(expand=c(0,0),breaks = c(2030,2040,2050))+
  scale_y_reverse(expand=c(0,0), breaks = c(0,1,2),labels=c("0%","1%","2%"))+
  facet_grid(Scenario~pkt_tot_variable)+
  scale_fill_gradientn(limits = c(50,160),
                       colours = c("#a50026","#ffffbf","#abd9e9","#313695"),
                       values = c(1,0.27,0.18,0),
                       breaks = seq(50,160,10),
                       labels = seq(50,160,10),
                       guide=guide_legend(title=expression(atop("GHG emissions","(Mt CO"[2]*" eq.)")),reverse = TRUE))+
  theme(axis.title = element_text(face = "plain"),
        axis.title.y = element_text(angle=90,margin = unit(c(0,2,0,1),"mm")),
        axis.title.x = element_text(margin = unit(c(2,0,1,0),"mm")),
        axis.text = element_text(size = rel(0.9)),
        axis.text.x = element_text(angle=40,vjust=1,hjust=1),
        axis.ticks = element_line(),
        legend.direction = "vertical",
        legend.text = element_text(size = rel(0.9)),
        legend.title.align = 0,
        legend.title = element_text(hjust=-1),
        legend.justification = "left",
        legend.key.size = unit(0.5,"cm"),
        plot.margin = unit(c(1,0,1,1),"mm"),
        strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
        panel.spacing.x = unit(0.2, "cm"),
        panel.spacing.y =unit(0.2, "cm"),
        strip.text = element_text(face="bold",margin = unit(c(1,1,1,1),"mm")),
        strip.text.y = element_text(angle=90))

plot+theme(legend.position="none")
ggsave("outputs/plots/paper/fig5.png",plot+theme(legend.position="none"),width=6,height=3.6,units=c("in"),dpi=600)

plot_legend <- get_legend(plot)
ggsave("outputs/plots/paper/fig5_leg.png",plot_legend,width=1.1,height=3,units=c("in"),dpi=600)

#Save
plot_dt$Simulation <- NULL
plot_dt$modal_share_variable <- paste0(plot_dt$modal_share_variable*100,"%")
colnames(plot_dt) <- rename_values(colnames(plot_dt),list(`Electrification target year`="electrification_year",`PT modal share change`="modal_share_variable",`Motorized pkt change`="pkt_tot_variable"))
plot_dt$Value <- formatC(plot_dt$Value/10^9, format = "e", digits = 2)
plot_dt$Unit <- "Mt CO2 eq."
write.csv(plot_dt,"outputs/raw_data/man_fig5.csv",row.names = FALSE)
```
